<table border="0" cellspacing="5" cellpadding="5">
	<tr>
		<th>First Name</th>
		<th>Middle Initial</th>
		<th>Last Name</th>
		<th>SSN</th>
		<th>Birthday</th>
		<th>Address</th>
		<th>Sex</th>
		<th>Salary</th>
	</tr>
	<?php foreach($this->employees as $employee): ?>
	<tr>
		<td><?php echo $employee->fname; ?></td>
		<td><?php echo $employee->minit; ?></td>
		<td><?php echo $employee->lname; ?></td>
		<td><?php echo $employee->ssn; ?></td>
		<td><?php echo $employee->bdate; ?></td>
		<td><?php echo $employee->address; ?></td>
		<td><?php echo $employee->sex; ?></td>
		<td><?php echo $employee->salary; ?></td>
	</tr>
	<?php endforeach; ?>
</table>