<p>
<?php echo $this->renderPartial('employees/_pagination'); ?>
</p>

<div id="ajax_employees"></div>

<p>Total records found: <?php echo $this->totalRecords; ?></p>

<p>
<?php echo $this->renderPartial('employees/_pagination'); ?>
</p>

<script type="text/javascript" charset="utf-8" src="/js/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/jquery.periodicalupdater.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/jquery.updater.js"></script>
<script>
	$.PeriodicalUpdater('/employees/ajax/', {
		  method: 'get',          // method; get or post
		  data: {p: <?php echo ($this->params['p'] ? $this->params['p'] : 1); ?>}, // array of values to be passed to the page - e.g. {name: "John", greeting: "hello"}
		  minTimeout: 1000*30,       // starting value for the timeout in milliseconds
		  maxTimeout: 8000*30,       // maximum length of time between requests
		  multiplier: 2,          // if set to 2, timerInterval will double each time the response hasn't changed (up to maxTimeout)
		  type: 'text',           // response type - text, xml, json, etc.  See $.ajax config options
		  maxCalls: 0,            // maximum number of calls. 0 = no limit.
		  autoStop: 0             // automatically stop requests after this many returns of the same data. 0 = disabled.
	}, function(data) {
		// Handle the new data (only called when there was a change)
		$('#ajax_employees').html(data);
	});
</script>