
<div id="results"></div>
<form action="new_submit" id="money_form" method="get" accept-charset="utf-8">
	<p>
		<label for="money">Enter your money amount: (ex: 1000.41)</label>
		<input type="text" name="money" value="" id="money" />
	</p>

	<p><input type="submit" value="Make Change &rarr;"></p>
</form>
<script type="text/javascript" charset="utf-8" src="/js/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/money.js"></script>
